steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/juegotetris/tetris-neon:${_COMMIT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/juegotetris/tetris-neon:${_COMMIT_SHA}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tetris-neon'
      - '--image'
      - 'gcr.io/juegotetris/tetris-neon:${_COMMIT_SHA}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--concurrency'
      - '80'
      - '--timeout'
      - '30'
      - '--cpu-throttling'

substitutions:
  _COMMIT_SHA: 'latest'

images:
  - 'gcr.io/juegotetris/tetris-neon:${_COMMIT_SHA}'